@startuml
(*) --> GebäudeVerwaltet
--> [input.Auftrag] PrüfauftragErteilt
--> [event.EtagePrüfungLäuft] PrüfauftragInArbeit
--> [event.EtageErledigt] PrüfauftragInArbeit
--> [event.AlleEtagenErledigt] PrüfauftragErledigt
--> RechnungDrucken
--> (*)
@enduml
